'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace SOServiceReference
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://www.prodigix.com/", ConfigurationName:="SOServiceReference.distributorWSSoap")>  _
    Public Interface distributorWSSoap
        
        'CODEGEN: Generating message contract since message VerifyUserRequest has headers
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.prodigix.com/VerifyUser", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function VerifyUser(ByVal request As SOServiceReference.VerifyUserRequest) As SOServiceReference.VerifyUserResponse
        
        'CODEGEN: Generating message contract since message VerifyDistIDUserRequest has headers
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.prodigix.com/VerifyDistIDUser", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function VerifyDistIDUser(ByVal request As SOServiceReference.VerifyDistIDUserRequest) As SOServiceReference.VerifyDistIDUserResponse
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.prodigix.com/")>  _
    Partial Public Class AuthHeader
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private authorizationKeyField As String
        
        Private domainField As String
        
        Private anyAttrField() As System.Xml.XmlAttribute
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property AuthorizationKey() As String
            Get
                Return Me.authorizationKeyField
            End Get
            Set
                Me.authorizationKeyField = value
                Me.RaisePropertyChanged("AuthorizationKey")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Domain() As String
            Get
                Return Me.domainField
            End Get
            Set
                Me.domainField = value
                Me.RaisePropertyChanged("Domain")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyAttributeAttribute()>  _
        Public Property AnyAttr() As System.Xml.XmlAttribute()
            Get
                Return Me.anyAttrField
            End Get
            Set
                Me.anyAttrField = value
                Me.RaisePropertyChanged("AnyAttr")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.prodigix.com/")>  _
    Partial Public Class WSResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private successField As Boolean
        
        Private messageField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property Success() As Boolean
            Get
                Return Me.successField
            End Get
            Set
                Me.successField = value
                Me.RaisePropertyChanged("Success")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property Message() As String
            Get
                Return Me.messageField
            End Get
            Set
                Me.messageField = value
                Me.RaisePropertyChanged("Message")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="VerifyUser", WrapperNamespace:="http://www.prodigix.com/", IsWrapped:=true)>  _
    Partial Public Class VerifyUserRequest
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://www.prodigix.com/")>  _
        Public AuthHeader As SOServiceReference.AuthHeader
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.prodigix.com/", Order:=0)>  _
        Public username As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.prodigix.com/", Order:=1)>  _
        Public password As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal AuthHeader As SOServiceReference.AuthHeader, ByVal username As String, ByVal password As String)
            MyBase.New
            Me.AuthHeader = AuthHeader
            Me.username = username
            Me.password = password
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="VerifyUserResponse", WrapperNamespace:="http://www.prodigix.com/", IsWrapped:=true)>  _
    Partial Public Class VerifyUserResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.prodigix.com/", Order:=0)>  _
        Public VerifyUserResult As SOServiceReference.WSResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal VerifyUserResult As SOServiceReference.WSResponse)
            MyBase.New
            Me.VerifyUserResult = VerifyUserResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="VerifyDistIDUser", WrapperNamespace:="http://www.prodigix.com/", IsWrapped:=true)>  _
    Partial Public Class VerifyDistIDUserRequest
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://www.prodigix.com/")>  _
        Public AuthHeader As SOServiceReference.AuthHeader
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.prodigix.com/", Order:=0)>  _
        Public distID As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal AuthHeader As SOServiceReference.AuthHeader, ByVal distID As Integer)
            MyBase.New
            Me.AuthHeader = AuthHeader
            Me.distID = distID
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="VerifyDistIDUserResponse", WrapperNamespace:="http://www.prodigix.com/", IsWrapped:=true)>  _
    Partial Public Class VerifyDistIDUserResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.prodigix.com/", Order:=0)>  _
        Public VerifyDistIDUserResult As SOServiceReference.WSResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal VerifyDistIDUserResult As SOServiceReference.WSResponse)
            MyBase.New
            Me.VerifyDistIDUserResult = VerifyDistIDUserResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface distributorWSSoapChannel
        Inherits SOServiceReference.distributorWSSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class distributorWSSoapClient
        Inherits System.ServiceModel.ClientBase(Of SOServiceReference.distributorWSSoap)
        Implements SOServiceReference.distributorWSSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SOServiceReference_distributorWSSoap_VerifyUser(ByVal request As SOServiceReference.VerifyUserRequest) As SOServiceReference.VerifyUserResponse Implements SOServiceReference.distributorWSSoap.VerifyUser
            Return MyBase.Channel.VerifyUser(request)
        End Function
        
        Public Function VerifyUser(ByVal AuthHeader As SOServiceReference.AuthHeader, ByVal username As String, ByVal password As String) As SOServiceReference.WSResponse
            Dim inValue As SOServiceReference.VerifyUserRequest = New SOServiceReference.VerifyUserRequest()
            inValue.AuthHeader = AuthHeader
            inValue.username = username
            inValue.password = password
            Dim retVal As SOServiceReference.VerifyUserResponse = CType(Me,SOServiceReference.distributorWSSoap).VerifyUser(inValue)
            Return retVal.VerifyUserResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SOServiceReference_distributorWSSoap_VerifyDistIDUser(ByVal request As SOServiceReference.VerifyDistIDUserRequest) As SOServiceReference.VerifyDistIDUserResponse Implements SOServiceReference.distributorWSSoap.VerifyDistIDUser
            Return MyBase.Channel.VerifyDistIDUser(request)
        End Function
        
        Public Function VerifyDistIDUser(ByVal AuthHeader As SOServiceReference.AuthHeader, ByVal distID As Integer) As SOServiceReference.WSResponse
            Dim inValue As SOServiceReference.VerifyDistIDUserRequest = New SOServiceReference.VerifyDistIDUserRequest()
            inValue.AuthHeader = AuthHeader
            inValue.distID = distID
            Dim retVal As SOServiceReference.VerifyDistIDUserResponse = CType(Me,SOServiceReference.distributorWSSoap).VerifyDistIDUser(inValue)
            Return retVal.VerifyDistIDUserResult
        End Function
    End Class
End Namespace
