'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class cover_photo_selection_edit

    '''<summary>
    '''frm1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frm1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''inner1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inner1 As Global.tsma.inner_header

    '''<summary>
    '''left1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents left1 As Global.tsma.headerleft

    '''<summary>
    '''spnCoverPhoto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spnCoverPhoto As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''hdnCoverPhotoContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnCoverPhotoContent As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnWidth As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnHeight As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnPublished control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnPublished As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''lblMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCoverPhotoName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCoverPhotoName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtUserEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUserEmail As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''lnkShareUserEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkShareUserEmail As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''objScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents objScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''divLib control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divLib As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''UpdateProgressLib control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdateProgressLib As Global.System.Web.UI.UpdateProgress

    '''<summary>
    '''uptMain1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uptMain1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txtname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtname As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divCoverPhotoHtml control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCoverPhotoHtml As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkFanPageName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkFanPageName As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''pnlEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlEdit As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''spnVideo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spnVideo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkReset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkReset As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lnkSaveName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkSaveName As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lnkSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkSave As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lnkPublish control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkPublish As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lnkDownload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkDownload As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''pnlMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlMessage As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''spnAssigned control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spnAssigned As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''hdnImageAreaW control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnImageAreaW As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnImageAreaH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnImageAreaH As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''inner2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inner2 As Global.tsma.inner_footer
End Class
