'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class customize_sweepstake_content

    '''<summary>
    '''Head1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

    '''<summary>
    '''FBApplicationId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FBApplicationId As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''linkpage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linkpage As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''divLiked1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divLiked1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divUnliked1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divUnliked1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''hdnFBUserId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnFBUserId As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnTSMAUserId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnTSMAUserId As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnFBPageId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnFBPageId As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnFBPageName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnFBPageName As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnFBApplicationId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnFBApplicationId As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnSweepStakeAppId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnSweepStakeAppId As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnSweepStakeAppName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnSweepStakeAppName As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnURL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnURL As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnShareText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnShareText As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnShareMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnShareMessage As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnShareImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnShareImage As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnEmailText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnEmailText As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnPDFlink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnPDFlink As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnlikeunlike control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnlikeunlike As Global.System.Web.UI.HtmlControls.HtmlInputHidden
End Class
