'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class headerleft

    '''<summary>
    '''ltrMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrMenu As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''trLegacy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trLegacy As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''trAmerifirst1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trAmerifirst1 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''trAmerifirst2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trAmerifirst2 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''trBoresha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trBoresha As Global.System.Web.UI.HtmlControls.HtmlTableRow
End Class
