'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class rajni_post2

    '''<summary>
    '''Head1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

    '''<summary>
    '''frm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frm As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.AjaxControlToolkit.ToolkitScriptManager

    '''<summary>
    '''inner1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inner1 As Global.tsma.inner_header

    '''<summary>
    '''left1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents left1 As Global.tsma.headerleft

    '''<summary>
    '''hdnselectedPages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnselectedPages As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnSelectedPagesName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnSelectedPagesName As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnSelectedPagesImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnSelectedPagesImage As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnselectedPagesAccessToken control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnselectedPagesAccessToken As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''txtMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMessage As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''AsyncFileUpload1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AsyncFileUpload1 As Global.AjaxControlToolkit.AsyncFileUpload

    '''<summary>
    '''myThrobber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents myThrobber As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgPhoto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgPhoto As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''lblVideoText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVideoText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hdnFBUserId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnFBUserId As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnImageUrl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnImageUrl As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''txtvideo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtvideo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''imgThumbnail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgThumbnail As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''plcData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plcData As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''dstFanPages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dstFanPages As Global.System.Web.UI.WebControls.DataList

    '''<summary>
    '''plcNoData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plcNoData As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''lnkSaveDraft control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkSaveDraft As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lnkPost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkPost As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''rptLibUserCatList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptLibUserCatList As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''txtNewLibCat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNewLibCat As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''lnkCreateNewCat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkCreateNewCat As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''txtActivationDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtActivationDate As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''selActivationHour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents selActivationHour As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''selActivationMinute control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents selActivationMinute As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''selAMPM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents selAMPM As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''ddlTimeZone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTimeZone As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lnkScheduledPost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkScheduledPost As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''hdnMakeDateString control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnMakeDateString As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''lblTimeZone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTimeZone As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hdnTimeZone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnTimeZone As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''inner2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inner2 As Global.tsma.inner_footer
End Class
