'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class scheduler_new

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''objScriptManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents objScriptManager As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''inner1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inner1 As Global.tsma.inner_header

    '''<summary>
    '''left1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents left1 As Global.tsma.headerleft

    '''<summary>
    '''lblMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hdnselectedPages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnselectedPages As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnSelectedPagesName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnSelectedPagesName As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnSelectedPagesImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnSelectedPagesImage As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnselectedPagesAccessToken control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnselectedPagesAccessToken As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''txtMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMessage As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''txtVideoMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVideoMessage As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''photo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents photo As Global.System.Web.UI.HtmlControls.HtmlInputFile

    '''<summary>
    '''imgPhoto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgPhoto As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''lblVideoText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVideoText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hdnImage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnImage1 As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnImageChange control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnImageChange As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''txtPhotoMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPhotoMessage As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''txtVideoLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVideoLink As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtLinkMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLinkMessage As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''txtvideo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtvideo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''imgThumbnail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgThumbnail As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''hdnUrl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnUrl As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnVideoId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnVideoId As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''lblFanPageMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFanPageMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''plcData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plcData As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''dstFanPages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dstFanPages As Global.System.Web.UI.WebControls.DataList

    '''<summary>
    '''plcNoData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plcNoData As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''lnkSaveDraft control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkSaveDraft As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lnkPost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkPost As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''rptLibUserCatList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptLibUserCatList As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''txtNewLibCat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNewLibCat As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''lnkCreateNewCat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkCreateNewCat As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''txtActivationDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtActivationDate As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''selActivationHour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents selActivationHour As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''selActivationMinute control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents selActivationMinute As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''selAMPM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents selAMPM As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''ddlTimeZone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTimeZone As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lnkScheduledPost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkScheduledPost As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''hdnMakeDateString control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnMakeDateString As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''lblTimeZone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTimeZone As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hdnTimeZone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnTimeZone As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''divHtml control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divHtml As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ltrLibraryTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrLibraryTotal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ltrLibraryTotal1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrLibraryTotal1 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ltrSchedluledTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrSchedluledTotal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ltrSentTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrSentTotal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ltrDraftTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrDraftTotal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''div5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div5 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''UpdateProgress4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdateProgress4 As Global.System.Web.UI.UpdateProgress

    '''<summary>
    '''ltrAdminLibMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrAdminLibMsg As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''trLibrary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trLibrary As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''rptAdminLibCatTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptAdminLibCatTitle As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''rptAdminLibCat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptAdminLibCat As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''ltrLibMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrLibMsg As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''rptUserLibCatTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptUserLibCatTitle As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''rptUserLibCat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptUserLibCat As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''ltrScheduledPosts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrScheduledPosts As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''dtlScheduledPosts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtlScheduledPosts As Global.System.Web.UI.WebControls.DataList

    '''<summary>
    '''phPagingScheduled control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phPagingScheduled As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''ltrSentItems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrSentItems As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''dtlSentItems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtlSentItems As Global.System.Web.UI.WebControls.DataList

    '''<summary>
    '''phPagingSent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phPagingSent As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''ltrDrafts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrDrafts As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''dtlDrafts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtlDrafts As Global.System.Web.UI.WebControls.DataList

    '''<summary>
    '''phPaging1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phPaging1 As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''hdnSetTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnSetTab As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''inner2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inner2 As Global.tsma.inner_footer
End Class
